# Generated by Django 5.1.5 on 2025-01-29 17:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('estatisticas', '0002_retirada'),
    ]

    operations = [
        migrations.AlterField(
            model_name='produto',
            name='classificacao',
            field=models.CharField(choices=[('Ácidos minerais oxidantes', 'Ácidos minerais oxidantes'), ('Bases cáusticas', 'Bases cáusticas'), ('Hidrocarbonetos aromáticos', 'Hidrocarbonetos aromáticos'), ('Orgânicos Halogenados', 'Orgânicos Halogenados'), ('Metais', 'Metais'), ('Metais tóxicos', 'Metais tóxicos'), ('Hidrocarbonetos alifáticos saturados', 'Hidrocarbonetos alifáticos saturados'), ('Fenóis e cresóis', 'Fenóis e cresóis'), ('Agentes oxidantes fortes', 'Agentes oxidantes fortes'), ('Agentes redutores fortes', 'Agentes redutores fortes'), ('Água e soluções aquosas', 'Água e soluções aquosas'), ('Substâncias que reagem com água', 'Substâncias que reagem com água'), ('Químicos tóxicos', 'Químicos tóxicos'), ('Inflamáveis', 'Inflamáveis'), ('Outros', 'Outros'), ('Não perigoso', 'Não perigoso')], max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='produto',
            name='quantidade',
            field=models.DecimalField(decimal_places=4, max_digits=19, null=True),
        ),
    ]
